import type { PracticeInterventionRequest, PracticeQuestionDraft } from "@/lib/learning/interventions/practice-request";
import type { PracticePaperQuestion } from "@/lib/practice/practice-papers";
import type { PracticePaperMarkSchemeItem } from "@/lib/practice/mark-schemes";

/**
 * The drafts as the stored shapes, once the student has agreed to them.
 *
 * Produces exactly what the existing practice pipeline already reads, so a
 * question generated by an intervention is sat, marked and turned into
 * evidence by the same code as any other -- there is no second marking path
 * and no second kind of practice question.
 *
 * The concept is attached here rather than inferred afterwards, which is what
 * makes the resulting attempts land on the right concept in the profile: see
 * `practicePaperObservations`.
 *
 * Pure, and outside the generator's server module on purpose: the generation
 * runs on a server and the confirmation runs in the student's browser, so the
 * one function both halves depend on cannot live behind `server-only`.
 */
export function practiceToStore(
  questions: readonly PracticeQuestionDraft[],
  request: Pick<PracticeInterventionRequest, "conceptId" | "interventionId">
): { questions: PracticePaperQuestion[]; markScheme: PracticePaperMarkSchemeItem[] } {
  const stored: PracticePaperQuestion[] = [];
  const markScheme: PracticePaperMarkSchemeItem[] = [];

  questions.forEach((question, index) => {
    const id = `q${index + 1}`;
    stored.push({
      id,
      label: `Question ${index + 1}`,
      prompt: question.prompt,
      marks: question.marks,
      assets: [],
      conceptIds: [request.conceptId],
    });
    markScheme.push({
      questionId: id,
      maxMarks: question.marks,
      answer: question.answer,
      acceptableAlternatives: [],
      commonMistakes: [],
      marking: "additive",
      points: question.points.map((point, pointIndex) => ({
        id: `${id}.${pointIndex + 1}`,
        marks: point.marks,
        code: "B",
        text: point.text,
        dep: [],
        ft: false,
        essentialTerms: [],
        allow: [],
        reject: [],
      })),
    });
  });

  return { questions: stored, markScheme };
}
